# Centralized version definition for release scripts
# Auto-generated by read_version_from_csproj.ps1 from: VRCSSDateTimeFixer.csproj
# Do not edit manually. Update the <Version> in the .csproj instead.
$version = "1.0.0"
