name: Feature request
description: "新しい機能の提案（タイトルは feat(scope): で始めてください）"
title: "feat(scope): "
labels:
  - type/feature
  - status/ready
  - priority/medium
assignees: []
body:
  - type: checkboxes
    id: area
    attributes:
      label: 対象領域（複数選択可）
      options:
        - label: area/cli
        - label: area/validators
        - label: area/services-timestamp
        - label: area/services-exif
    validations:
      required: false
  - type: input
    id: scope
    attributes:
      label: scope（タイトルの scope に入れる簡潔な領域名）
      placeholder: cli / validators / services-exif など
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: どのような機能を追加したいか、ユーザ視点で簡潔に
      placeholder: 例）ワイルドカード指定（*.png, **/*.jpg）でファイルを処理対象にできるようにする
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: 背景 / 動機
      description: なぜ必要か、関連する仕様・README・既存機能
    validations:
      required: false
  - type: textarea
    id: requirements
    attributes:
      label: 機能要件
      description: 箇条書きで要件を記載
      placeholder: |
        - 例）`*.png`, `**/*.png` を解釈する
        - 例）重複排除、0件時は非0終了
    validations:
      required: false
  - type: textarea
    id: acceptance
    attributes:
      label: 受け入れ条件（Acceptance Criteria）
      description: 成功条件を具体的に
    validations:
      required: false
  - type: textarea
    id: tests
    attributes:
      label: テスト観点（GWT形式）
      description: Given-When-Then で記述（日本語）
      placeholder: |
        - Given: C:\Shots に a.png, b.jpg
          When: VRCSSDateTimeFixer "C:\\Shots\\*.png" を実行
          Then: a.png のみ処理される
    validations:
      required: false
  - type: checkboxes
    id: practice
    attributes:
      label: 開発プラクティス
      options:
        - label: practice/tdd を適用する（TDDで実装）
    validations:
      required: false
